FROM ubuntu:18.04

RUN \
  apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends apt-utils && \
  apt-get install -y python python-dev python-pip python-virtualenv git && \
  rm -rf /var/lib/apt/lists/*

RUN \
  cd /opt && \
  git clone https://github.com/MarceloCorpucci/effective-testing.git && \
  cd effective-testing && \
  pip install -r requirements.txt && \
  chown -R $USER:$USER /opt/effective-testing

EXPOSE 5000

